name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Update package.json version
        if: ${{ success() }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          export NEW_VERSION=$(npx -q semver $(cat package.json | jq -r .version) -i patch)
          npm version --no-git-tag-version --allow-same-version $NEW_VERSION
          git add package.json
          git commit -m "chore: update version in package.json to $NEW_VERSION"
          git push
    permissions:
      contents: write
